# Generated by Django 5.2.1 on 2025-05-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='bookingdate',
        ),
    ]
